# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("https://www.facebook.com/")
    self.driver.set_window_size(1551, 1020)
    element = self.driver.find_element(By.CSS_SELECTOR, ".loggedout_menubar")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".loggedout_menubar")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".loggedout_menubar")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".loggedout_menubar").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2)").click()
    self.driver.find_element(By.ID, "pass").send_keys("Siniyiney7")
    self.driver.find_element(By.ID, "pass").send_keys(Keys.ENTER)
  
